module.exports =
  NODE_ENV: 'development'
  PORT: 3000
  MONGO_URL: 'mongodb://localhost:27017/erp'
  REDIS_HOST: 'localhost'
  REDIS_PORT: 6379
  REDIS_DATABASE: 11
  #REDIS_PASSWORD: ''
  SESSION_SECRET: '43j;lkd90bvcs1'